/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Acer
 */
public class PerhitunganDiskonFrame extends javax.swing.JFrame {

    /**
     * Creates new form PerhitunganDiskonFrame
     */
    public PerhitunganDiskonFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        cbbDiskon = new javax.swing.JComboBox<>();
        txtHargaAkhir = new javax.swing.JTextField();
        txtPenghematan = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtKuponDiskon = new javax.swing.JTextField();
        slDiskon = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRiwayat = new javax.swing.JTextArea();

        jLabel5.setText("jLabel5");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Harga Asli");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Pilih Persentase Diskon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Harga Akhir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Jumlah Penghematan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel4, gridBagConstraints);

        txtHarga.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(txtHarga, gridBagConstraints);

        cbbDiskon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "25" }));
        cbbDiskon.setPreferredSize(new java.awt.Dimension(100, 24));
        cbbDiskon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbDiskonItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(cbbDiskon, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(txtHargaAkhir, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(txtPenghematan, gridBagConstraints);

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(btnHitung, gridBagConstraints);

        jLabel6.setText("Kupon Diskon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(txtKuponDiskon, gridBagConstraints);

        slDiskon.setMajorTickSpacing(25);
        slDiskon.setMinorTickSpacing(5);
        slDiskon.setPaintLabels(true);
        slDiskon.setPaintTicks(true);
        slDiskon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slDiskonStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(slDiskon, gridBagConstraints);

        txtRiwayat.setColumns(20);
        txtRiwayat.setRows(5);
        jScrollPane1.setViewportView(txtRiwayat);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void hitungDiskon() {
        // Mengambil harga asli dari text field
        String hargaAsliText = txtHarga.getText();

        try {
            // Mengonversi harga asli ke tipe data double
            double hargaAsli = Double.parseDouble(hargaAsliText);

            // Mengambil nilai diskon dari slider
            int diskon = slDiskon.getValue();  // Ambil nilai persentase diskon dari slider

            // Menghitung jumlah penghematan dari diskon utama
            double penghematan = hargaAsli * (diskon / 100.0);

            // Menghitung harga akhir setelah diskon utama
            double hargaAkhir = hargaAsli - penghematan;

            // Mendapatkan nilai kupon diskon dari txtKuponDiskon (berupa teks)
            String kuponText = txtKuponDiskon.getText().trim();  // Menghapus spasi ekstra

            // Menentukan diskon kupon berdasarkan kode kupon
            double kuponDiskon = 0.0;

            // Contoh kode kupon yang valid dan nilai diskonnya
            if (kuponText.equalsIgnoreCase("DISKON10")) {
                kuponDiskon = 10;  // 10% diskon
            } else if (kuponText.equalsIgnoreCase("DISKON20")) {
                kuponDiskon = 20;  // 20% diskon
            } else if (kuponText.equalsIgnoreCase("DISKON50")) {
                kuponDiskon = 50;  // 50% diskon
            }

            // Jika ada kupon yang valid, hitung diskon tambahan
            if (kuponDiskon > 0) {
                // Terapkan diskon tambahan kupon ke harga akhir
                hargaAkhir -= hargaAkhir * (kuponDiskon / 100.0);
                // Hitung penghematan tambahan
                penghematan += hargaAsli * (kuponDiskon / 100.0);
            } else if (!kuponText.isEmpty()) {
                // Jika kupon tidak valid (tidak cocok dengan kode yang ada)
                javax.swing.JOptionPane.showMessageDialog(this, "Kode kupon tidak valid!", "Error Kupon", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Menampilkan hasil perhitungan pada text field
            txtPenghematan.setText(String.format("%.2f", penghematan));
            txtHargaAkhir.setText(String.format("%.2f", hargaAkhir));

            // Menambahkan riwayat perhitungan ke textarea txtRiwayat
            String riwayat = "Harga Asli: " + String.format("%.2f", hargaAsli) + "\n"
                    + "Diskon: " + diskon + "%\n"
                    + "Penghematan: " + String.format("%.2f", penghematan) + "\n"
                    + "Harga Akhir: " + String.format("%.2f", hargaAkhir) + "\n"
                    + "==============================\n";

            // Menambahkan riwayat ke TextArea (txtRiwayat)
            txtRiwayat.append(riwayat); // .append() digunakan untuk menambahkan teks ke akhir textarea

        } catch (NumberFormatException e) {
            // Menangani kesalahan jika input harga bukan angka
            javax.swing.JOptionPane.showMessageDialog(this, "Mohon masukkan harga yang valid!", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        hitungDiskon();
    }//GEN-LAST:event_btnHitungActionPerformed

    private void cbbDiskonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbDiskonItemStateChanged
        slDiskon.setValue(Integer.parseInt(cbbDiskon.getSelectedItem().toString()));

    }//GEN-LAST:event_cbbDiskonItemStateChanged

    private void slDiskonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slDiskonStateChanged
        
    }//GEN-LAST:event_slDiskonStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerhitunganDiskonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerhitunganDiskonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerhitunganDiskonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerhitunganDiskonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerhitunganDiskonFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JComboBox<String> cbbDiskon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JSlider slDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtHargaAkhir;
    private javax.swing.JTextField txtKuponDiskon;
    private javax.swing.JTextField txtPenghematan;
    private javax.swing.JTextArea txtRiwayat;
    // End of variables declaration//GEN-END:variables
}
